version: "3"

services:
  backend:
    restart: unless-stopped
    build: ./backend
    container_name: uygo_backend
    volumes:
      - ./backend:/usr/src/app/backend
      - static_volume:/usr/src/app/backend/assets
      - database_volume:/var/lib/postgresql/data:ro
    entrypoint: /usr/src/app/backend/backend-entrypoint.sh
    ports:
      - "5100:5100"
    depends_on:
      - db
    env_file:
      - ./backend/.env
  db:
    restart: unless-stopped
    image: postgres:11
    volumes:
      - database_volume:/var/lib/postgresql/data:ro
    expose:
      - 5432
    environment:
      POSTGRES_PASSWORD: postgres
  nginx:
    image: nginx:alpine
    ports:
      - "5000:8080"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf:ro
      - static_volume:/static
    depends_on:
      - backend
volumes:
  database_volume:
  static_volume:
