version: "3"

services:
  backend:
    restart: unless-stopped
    build: ./backend
    container_name: uygo_backend
    volumes:
      - ./backend:/usr/src/app/backend
      - static_volume:/usr/src/app/backend/assets
      - database_volume:/var/lib/postgresql/data
    entrypoint: /usr/src/app/backend/backend-entrypoint.sh
    ports:
      - "5100:5100"
    depends_on:
      - db
    env_file:
      - ./.env
  db:
    restart: unless-stopped
    image: postgres:11
    volumes:
      - database_volume:/var/lib/postgresql/data
    expose:
      - 5432
    env_file:
      - ./.env
  nginx:
    image: nginx:alpine
    ports:
      - "5000:80"
    volumes:
      - ./nginx/dev.conf:/etc/nginx/conf.d/default.conf
      - static_volume:/static
    depends_on:
      - backend
  redis:
    image: redis:alpine
  celery:
    restart: unless-stopped
    build: ./backend
    command: celery -A backend worker -l info
    volumes:
      - ./backend:/usr/src/app/backend
    env_file:
      - ./.env
    depends_on:
      - db
      - redis
      - backend
volumes:
  database_volume:
  static_volume:
