# Generated by Django 3.1 on 2021-04-20 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('is_superuser', models.BooleanField(default=False, help_text='Designates that this user has all permissions without explicitly assigning them.', verbose_name='superuser status')),
                ('login', models.CharField(max_length=200, unique=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, help_text='The groups this user belongs to. A user will get all permissions granted to each of their groups.', related_name='user_set', related_query_name='user', to='auth.Group', verbose_name='groups')),
                ('user_permissions', models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.Permission', verbose_name='user permissions')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('type', models.IntegerField(choices=[(1, 'admin'), (2, 'cashier')], default=2)),
                ('fullname', models.CharField(max_length=200)),
                ('last_worked', models.DateTimeField(auto_now=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.CreateModel(
            name='Depot',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user', models.Model),
        ),
        migrations.CreateModel(
            name='Store',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
                ('name', models.CharField(max_length=200, null=True)),
                ('address', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('phone', models.CharField(max_length=200)),
                ('email', models.EmailField(blank=True, max_length=200, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user', models.Model),
        ),
    ]
