# Generated by Django 3.1 on 2021-04-20 06:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210420_1218'),
        ('admin', '0003_logentry_add_action_flag_choices'),
        ('authtoken', '0002_auto_20160226_1747'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Manager',
            fields=[
                ('user_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='user.user')),
            ],
            options={
                'abstract': False,
            },
            bases=('user.user',),
        ),
        migrations.RemoveField(
            model_name='store',
            name='user_ptr',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='login',
            new_name='username',
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='fullname',
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='last_worked',
        ),
        migrations.RemoveField(
            model_name='cashier',
            name='type',
        ),
        migrations.AddField(
            model_name='cashier',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='item.store'),
        ),
        migrations.AddField(
            model_name='user',
            name='first_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='user',
            name='last_name',
            field=models.CharField(default='', max_length=200),
            preserve_default=False,
        ),
        migrations.DeleteModel(
            name='Depot',
        ),
        migrations.DeleteModel(
            name='Store',
        ),
    ]
