# Generated by Django 3.1 on 2021-04-21 06:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20210421_1252'),
        ('user', '0002_auto_20210420_1218'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cashier',
            name='store',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='cashiers', to='item.store'),
            preserve_default=False,
        ),
    ]
