# Generated by Django 3.1 on 2021-04-27 11:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0004_client'),
    ]

    operations = [
        migrations.AddField(
            model_name='client',
            name='type',
            field=models.IntegerField(choices=[(0, 'Обычный'), (1, 'Пенсионер')], default=0),
        ),
    ]
