# Generated by Django 3.1 on 2021-04-20 03:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('item', '0001_initial'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='depot',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='depot', to='user.depot'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='store', to='user.store'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='global_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.globalitem'),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='items', to='user.store'),
        ),
        migrations.AddField(
            model_name='globalitem',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='item.category'),
        ),
        migrations.AddField(
            model_name='clientordereditem',
            name='client_order',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_ordered_items', to='item.clientorder'),
        ),
        migrations.AddField(
            model_name='clientordereditem',
            name='global_item',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_ordered_items', to='item.globalitem'),
        ),
        migrations.AddField(
            model_name='clientorder',
            name='cashier',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='client_orders', to='user.cashier'),
        ),
        migrations.AddField(
            model_name='category',
            name='store',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='user.store'),
        ),
        migrations.AddField(
            model_name='cashierhistory',
            name='cashier',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.cashier'),
        ),
        migrations.AddField(
            model_name='cashierhistory',
            name='client_orders',
            field=models.ManyToManyField(to='item.ClientOrder'),
        ),
    ]
