# Generated by Django 3.1 on 2021-04-20 11:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0003_auto_20210420_1218'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalitem',
            options={'ordering': ['name']},
        ),
    ]
