# Generated by Django 3.1 on 2021-04-20 11:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0004_auto_20210420_1725'),
    ]

    operations = [
        migrations.AddIndex(
            model_name='storeitem',
            index=models.Index(fields=['store'], name='store_index'),
        ),
    ]
