# Generated by Django 3.1 on 2021-04-21 06:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0005_auto_20210420_1728'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'ordering': ['total_quantity']},
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='status',
        ),
        migrations.AlterField(
            model_name='clientorder',
            name='status',
            field=models.IntegerField(choices=[(1, 'Новые'), (2, 'Упаковывается'), (3, 'В пути'), (4, 'Завершенные'), (5, 'Отказано')], default=1),
        ),
    ]
