# Generated by Django 3.1 on 2021-04-21 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0006_auto_20210421_1252'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='storeitem',
            constraint=models.UniqueConstraint(fields=('store', 'global_item'), name='unique_store_global_item'),
        ),
    ]
