# Generated by Django 3.1 on 2021-04-22 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0007_auto_20210421_1604'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='total_cnt',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='unique_id',
        ),
    ]
