# Generated by Django 3.1 on 2021-04-22 07:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0008_auto_20210422_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientordereditem',
            name='cost_one',
            field=models.FloatField(default=0),
        ),
        migrations.AlterField(
            model_name='clientordereditem',
            name='cost_total',
            field=models.FloatField(default=0, null=True),
        ),
    ]
