# Generated by Django 3.1 on 2021-04-23 06:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0011_auto_20210423_1216'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='store',
        ),
    ]
