# Generated by Django 3.1 on 2021-04-23 07:29

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0012_remove_category_store'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='total_cost',
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='quantity',
            field=models.FloatField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
