# Generated by Django 3.1 on 2021-04-23 07:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0013_auto_20210423_1329'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeitem',
            name='parts',
        ),
    ]
