# Generated by Django 3.1 on 2021-04-23 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0014_remove_storeitem_parts'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeitem',
            name='parts',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
