# Generated by Django 3.1 on 2021-04-23 08:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0015_storeitem_parts'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={},
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_cost',
        ),
        migrations.RemoveField(
            model_name='category',
            name='total_quantity',
        ),
    ]
