# Generated by Django 3.1 on 2021-04-26 09:52

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0016_auto_20210423_1423'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalitem',
            name='sepparts',
        ),
        migrations.AddField(
            model_name='globalitem',
            name='num_pieces',
            field=models.IntegerField(default=1),
        ),
        migrations.AddField(
            model_name='storeitem',
            name='num_pieces',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storeitem',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
