# Generated by Django 3.1 on 2021-04-26 10:15

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0017_auto_20210426_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorderitem',
            name='num_pieces',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='quantity',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
    ]
