# Generated by Django 3.1 on 2021-04-26 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0018_auto_20210426_1615'),
    ]

    operations = [
        migrations.RenameField(
            model_name='globalitem',
            old_name='num_pieces',
            new_name='max_num_pieces',
        ),
    ]
