# Generated by Django 3.1 on 2021-04-26 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0020_auto_20210426_1744'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storeorder',
            name='next',
        ),
    ]
