# Generated by Django 3.1 on 2021-04-27 03:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0021_remove_storeorder_next'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoreOrderHistory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('store_order_data', models.JSONField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('store_order', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='history', to='item.storeorder')),
            ],
            options={
                'ordering': ('store_order', 'created_at'),
            },
        ),
    ]
