# Generated by Django 3.1 on 2021-04-27 06:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0023_auto_20210427_1042'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientordereditem',
            name='sepparts',
        ),
        migrations.AddField(
            model_name='clientordereditem',
            name='num_pieces',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='clientordereditem',
            name='global_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.globalitem'),
        ),
        migrations.AlterField(
            model_name='clientordereditem',
            name='quantity',
            field=models.IntegerField(default=1, validators=[django.core.validators.MinValueValidator(1)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='global_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='item.globalitem'),
        ),
    ]
