# Generated by Django 3.1 on 2021-04-27 09:01

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0024_auto_20210427_1256'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='clientordereditem',
            name='date_ordered',
        ),
        migrations.AlterField(
            model_name='clientordereditem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='quantity',
            field=models.IntegerField(validators=[django.core.validators.MinValueValidator(0)]),
        ),
        migrations.AlterField(
            model_name='storeorderitem',
            name='store_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='ordered_items', to='item.storeorder'),
        ),
    ]
