# Generated by Django 3.1 on 2021-04-27 09:21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0025_auto_20210427_1501'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storeorderitem',
            name='store_order',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store_ordered_items', to='item.storeorder'),
        ),
    ]
