# Generated by Django 3.1 on 2021-04-27 11:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('item', '0027_auto_20210427_1707'),
    ]

    operations = [
        migrations.DeleteModel(
            name='DiscountTypes',
        ),
    ]
