# Generated by Django 3.1 on 2021-01-26 10:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('totalCost', models.FloatField(default=0)),
                ('totalQuantity', models.FloatField(default=0)),
                ('storeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='store', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='GlobalItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(blank=True, max_length=200)),
                ('name', models.CharField(max_length=200)),
                ('description', models.TextField()),
                ('image', models.TextField(blank=True, null=True)),
                ('category', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.category')),
            ],
        ),
        migrations.CreateModel(
            name='ItemsIn',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.TextField(blank=True, null=True)),
                ('datesent', models.DateTimeField(auto_now_add=True, null=True)),
                ('datereceived', models.DateTimeField(auto_now_add=True, null=True)),
                ('totalCount', models.IntegerField(default=0)),
                ('totalCost', models.FloatField(default=0)),
                ('status', models.BooleanField(default=False)),
                ('storedepotid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storedepotid', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='StoreOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cost', models.FloatField()),
                ('itemglobal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeorder', to='core.globalitem')),
                ('itemin', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.itemsin')),
            ],
        ),
        migrations.CreateModel(
            name='Item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(blank=True, null=True)),
                ('costin', models.FloatField()),
                ('costsale', models.FloatField()),
                ('itemglobal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemglobal', to='core.globalitem')),
                ('storeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='activestore', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
