# Generated by Django 3.1 on 2021-01-26 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_category_globalitem_item_itemsin_storeorder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalitem',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
