# Generated by Django 3.1 on 2021-01-26 11:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_auto_20210126_1722'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsin',
            name='uniqueid',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
