# Generated by Django 3.1 on 2021-01-26 12:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_itemsin_uniqueid'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderReceived',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('orderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.itemsin')),
            ],
        ),
    ]
