# Generated by Django 3.1 on 2021-01-27 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_orderreceived'),
    ]

    operations = [
        migrations.AlterField(
            model_name='item',
            name='costsale',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
