# Generated by Django 3.1 on 2021-01-27 05:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_checkusername'),
    ]

    operations = [
        migrations.CreateModel(
            name='CashierLogin',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('phone', models.CharField(max_length=200)),
                ('password', models.CharField(max_length=200)),
                ('lastdate', models.DateTimeField(auto_now_add=True, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Cashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fullname', models.CharField(max_length=200)),
                ('phone', models.CharField(max_length=50)),
                ('type', models.CharField(choices=[(1, 'admin'), (2, 'cashier')], max_length=200, null=True)),
                ('password', models.CharField(max_length=200)),
                ('lastdate', models.CharField(blank=True, max_length=200, null=True)),
                ('finishdayid', models.IntegerField(blank=True, null=True)),
                ('store', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
