# Generated by Django 3.1 on 2021-01-27 05:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_cashier_cashierlogin'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('countitem', models.IntegerField(null=True)),
                ('total', models.FloatField(default=0)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cashier')),
            ],
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datefrom', models.DateField(blank=True, null=True)),
                ('dateto', models.DateField(blank=True, null=True)),
                ('inTotal', models.IntegerField(default=0)),
                ('incomeTotal', models.IntegerField(default=0)),
                ('earnTotal', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='FinishCashier',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datestart', models.DateTimeField(blank=True, null=True)),
                ('dateend', models.DateTimeField(blank=True, null=True)),
                ('total', models.FloatField(blank=True, null=True)),
                ('tottrans', models.FloatField(blank=True, null=True)),
                ('cashier', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cashier')),
                ('transactions', models.ManyToManyField(to='core.ClientOrder')),
            ],
        ),
        migrations.CreateModel(
            name='ClientOrderItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.FloatField(null=True)),
                ('date', models.DateTimeField(auto_now_add=True, null=True)),
                ('costone', models.FloatField()),
                ('costtotal', models.FloatField(default=0)),
                ('itemglobal', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='core.globalitem')),
                ('transaction', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientorder')),
            ],
        ),
        migrations.CreateModel(
            name='CashierID',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('finishdayid', models.IntegerField(blank=True, null=True)),
                ('datetime', models.DateTimeField(auto_now_add=True, null=True)),
                ('cashierid', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.cashier')),
            ],
        ),
    ]
