# Generated by Django 3.1 on 2021-01-27 08:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_cashierid_clientorder_clientorderitem_finishcashier_report'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientorderitem',
            old_name='transaction',
            new_name='clientorder',
        ),
    ]
