# Generated by Django 3.1 on 2021-01-27 08:29

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0010_auto_20210127_1424'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorderitem',
            name='clientorder',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientorder'),
        ),
    ]
