# Generated by Django 3.1 on 2021-01-27 09:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_auto_20210127_1429'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientorderitem',
            name='clientorder',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientorder'),
        ),
    ]
