# Generated by Django 3.1 on 2021-01-27 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_auto_20210127_1509'),
    ]

    operations = [
        migrations.RenameField(
            model_name='clientorderitem',
            old_name='clientorder',
            new_name='transactionid',
        ),
    ]
