# Generated by Django 3.1 on 2021-01-29 11:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_auto_20210127_1544'),
    ]

    operations = [
        migrations.CreateModel(
            name='AddStoreItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('uniqueid', models.CharField(max_length=200)),
                ('cost', models.FloatField()),
                ('quantity', models.IntegerField()),
                ('storeid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='itemadd', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
