# Generated by Django 3.1 on 2021-02-01 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_addstoreitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='storeorder',
            name='costTotal',
            field=models.FloatField(default=0),
        ),
    ]
