# Generated by Django 3.1 on 2021-02-02 05:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_storeorder_costtotal'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsin',
            name='depotid',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='depotid', to=settings.AUTH_USER_MODEL),
        ),
    ]
