# Generated by Django 3.1 on 2021-02-03 06:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_itemsin_depotid'),
    ]

    operations = [
        migrations.AddField(
            model_name='itemsin',
            name='iseditable',
            field=models.BooleanField(default=True),
        ),
    ]
