# Generated by Django 3.1 on 2021-03-16 16:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_auto_20210217_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalitem',
            name='producer',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='globalitem',
            name='uniqueid',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.CreateModel(
            name='FarmStoreItems',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('seria', models.CharField(max_length=200, null=True)),
                ('deadline', models.DateField()),
                ('cost', models.FloatField()),
                ('globalitem', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='core.globalitem')),
            ],
        ),
    ]
