# Generated by Django 3.1 on 2021-03-16 16:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_auto_20210316_2228'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='item',
            name='costin',
        ),
        migrations.AddField(
            model_name='item',
            name='issale',
            field=models.BooleanField(default=False),
        ),
    ]
