# Generated by Django 3.1 on 2021-03-16 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_auto_20210316_2253'),
    ]

    operations = [
        migrations.AddField(
            model_name='item',
            name='costin',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
