# Generated by Django 3.1 on 2021-03-16 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_item_costin'),
    ]

    operations = [
        migrations.AlterField(
            model_name='farmstoreitems',
            name='deadline',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
