# Generated by Django 3.1 on 2021-03-17 08:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_auto_20210317_0111'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='addstoreitem',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='clientorderitem',
            name='itemglobal',
        ),
        migrations.RemoveField(
            model_name='item',
            name='itemglobal',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='cost',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='itemglobal',
        ),
        migrations.AddField(
            model_name='addstoreitem',
            name='sepparts',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='addstoreitem',
            name='seria',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='clientorderitem',
            name='farmstoreitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='transaction', to='core.farmstoreitems'),
        ),
        migrations.AddField(
            model_name='clientorderitem',
            name='sepparts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='item',
            name='farmstoreitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.farmstoreitems'),
        ),
        migrations.AddField(
            model_name='item',
            name='sepparts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='farmstoreitems',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='storeorder', to='core.farmstoreitems'),
        ),
        migrations.AddField(
            model_name='storeorder',
            name='sepparts',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='addstoreitem',
            name='quantity',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='addstoreitem',
            name='uniqueid',
            field=models.CharField(max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='clientorderitem',
            name='quantity',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='item',
            name='issale',
            field=models.BooleanField(default=False, null=True),
        ),
        migrations.AlterField(
            model_name='storeorder',
            name='quantity',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
