# Generated by Django 3.1 on 2021-03-18 06:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_auto_20210317_1449'),
    ]

    operations = [
        migrations.RenameField(
            model_name='item',
            old_name='costin',
            new_name='parts',
        ),
        migrations.RenameField(
            model_name='item',
            old_name='sepparts',
            new_name='totalcost',
        ),
        migrations.RemoveField(
            model_name='storeorder',
            name='sepparts',
        ),
        migrations.AddField(
            model_name='farmstoreitems',
            name='sepparts',
            field=models.FloatField(null=True),
        ),
        migrations.AddField(
            model_name='farmstoreitems',
            name='totalcost',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
