# Generated by Django 3.1 on 2021-03-18 10:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_auto_20210318_1239'),
    ]

    operations = [
        migrations.AddField(
            model_name='clientorder',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.CreateModel(
            name='OrderReceivedClient',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('clientorderid', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='core.clientorder')),
            ],
        ),
    ]
