# Generated by Django 3.1 on 2021-03-19 11:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_auto_20210318_1840'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='globalitem',
            options={'ordering': ['id']},
        ),
        migrations.RemoveField(
            model_name='category',
            name='storeid',
        ),
    ]
