# Generated by Django 3.1 on 2021-03-24 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0029_category_storeid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(1, 'depot'), (2, 'store')], max_length=200),
        ),
    ]
