# Generated by Django 3.1 on 2021-03-24 18:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_auto_20210325_0003'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='type',
            field=models.CharField(choices=[(1, 'store'), (2, 'depot')], default=1, max_length=50),
        ),
    ]
